trial, result, optimal, taken
0,Crashed Traceback (most recent call last):  File "/Users/admin/Documents/nethack-deterministic/effectiveness-study.py", line 13, in <module>    result, optimal, moves = agent.play()  File "/Users/admin/Documents/nethack-deterministic/Agent.py", line 56, in play    _, destination = heappop(self.pQueue)IndexError: index out of range,0,0
1,True,16,15
